### ISSUE TITLE
Player does not stop after upgrade to v1.80.2

### ISSUE THREAD

**Issue by rgreil** [philippe44/LMS-uPnP#55]
Hi,

are there any know issues with v1.80.2?
After I've upgrade the plugin in LMS to v1.80.2, the player does not stop any longer.
Stopping via stop button or player on/off toggle does not make a differenct.

**Comment by philippe44** [comment]
None that I'ma ware of and that casue that. I've alos pushed some minor tweaks in 1.80.3. Can you describe a bit more what's happenign 'player, LMS version, OS, CPU, what's being played...) and put a log?

**Comment by rgreil** [comment]
Looks like it only happens with internet radio. See log attached. After sending the pause, the stream showes stopped in LMS but still playing.

Logitech Media Server Version: 8.2.0 - 1627922070 @ Tue Aug 3 11:43:18 CEST 2021
OS: piCore - DE - utf8
Plattformarchitecture: aarch64-linux
Perl-Version: 5.32.1 - aarch64-linux-thread-multi
Hardware: Raspberry Pi 3 Model B

Player: Yamaha RXV477

**Comment by philippe44** [comment]
Are you sure there is a log?

**Comment by rgreil** [comment]
my fault, log is here:

[06:53:15.577987] output_http_thread:389 [0x4bcf00]: end thread 0 (6422528 bytes)
[06:53:15.582187] sendSTAT:169 [0x4bcf00]: STAT:[STMf] msplayed 0
[06:53:15.582740] AVTStop:217 [0x546ed0]: uPNP stop (cookie 0x1c4)
[06:53:15.988244] _SyncNotifState:656 [0x546ed0]: uPNP stop
[06:53:16.020398] process_strm:238 [0x4bcf00] strm command s
[06:53:16.020515] process_strm:307 [0x4bcf00], strm s autostart: 3 transition period: 10 transition type: 0 codec: m
[06:53:16.020555] sendSTAT:169 [0x4bcf00]: STAT:[STMf] msplayed 0
[06:53:16.063765] output_start:81 [0x4bcf00]: start thread 0
[06:53:16.064300] sq_callback:343 [0x546ed0]:
	artist:
	album:
	title:Hitradio Ã–3 88.2 (Top 40/Pop)
	genre:
	duration:0.000
	size:0
	cover:http://192.168.1.15:9000/imageproxy/http%3A%2F%2Fcdn-profiles.tunein.com%2Fs8007%2Fimages%2Flogoq.png%3Ft%3D159965/image.png
	offset:0
[06:53:16.064404] sq_callback:382 [0x546ed0]: set current URI (s:0) http://192.168.1.15:49431/bridge-7.mp3
[06:53:16.064786] AVTSetURI:91 [0x546ed0]: uPNP setURI http://192.168.1.15:49431/bridge-7.mp3 (cookie 0x1c6)
[06:53:16.065810] process_start:1220 [0x4bcf00]: codec:*, ch:0, s:0, r:0
[06:53:16.095087] sendSTAT:169 [0x4bcf00]: STAT:[STMc] msplayed 0
[06:53:16.300769] AVTSetPlayMode:167 [0x546ed0]: uPNP set play mode (cookie 0x1c7)
[06:53:16.301070] AVTPlay:151 [0x546ed0]: uPNP play (cookie 0x1c7)
[06:53:16.301197] CtrlSetVolume:245 [0x546ed0]: uPNP volume 35 (cookie 0x1c7)
[06:53:16.395784] output_http_thread:157 [0x4bcf00]: got HTTP connection 13
[06:53:16.395920] output_http_thread:186 [0x4bcf00]: drain is 2621440 (waited 331)
[06:53:16.401705] handle_http:483 [0x4bcf00]: received GET /bridge-7.mp3 HTTP/1.1
[06:53:16.401774] handle_http:486 [0x4bcf00]: HTTP headers
Host: 192.168.1.15:49431
Icy-MetaData: 1
Connection: close
transferMode.dlna.org: Streaming
User-Agent: WinampMPEG/2.8
Accept: */*

[06:53:16.402036] handle_http:570 [0x4bcf00]: responding:
HTTP/1.1 200 OK
Server: squeezebox-bridge
Connection: close
icy-metaint: 16384
Content-Type: audio/mpeg
transferMode.dlna.org: Streaming
Transfer-Encoding: chunked


[06:53:16.402894] send_with_icy:425 [0x4bcf00]: ICY update
	
	Hitradio Ã–3 88.2 (Top 40/Pop)
	http://192.168.1.15:9000/imageproxy/http%3A%2F%2Fcdn-profiles.tunein.com%2Fs8007%2Fimages%2Flogoq.png%3Ft%3D159965/image.png
[06:53:16.564385] _SyncNotifState:634 [0x546ed0]: uPNP transition
[06:53:21.489536] _SyncNotifState:684 Wohnzimmer: uPNP playing
[06:53:21.537059] sendSTAT:169 [0x4bcf00]: STAT:[STMs] msplayed 0
[06:53:21.899867] send_with_icy:425 [0x4bcf00]: ICY update
	HITRADIO Ã–3
	Livestream
	http://192.168.1.15:9000/imageproxy/http%3A%2F%2Fcdn-profiles.tunein.com%2Fs8007%2Fimages%2Flogoq.png%3Ft%3D159965/image.png
[06:53:27.280634] send_with_icy:425 [0x4bcf00]: ICY update
	HITRADIO Ã–3
	Livestream
	http://cdn-albums.tunein.com/gn/6Z596KGP32g.jpg
[06:53:30.262952] process_strm:238 [0x4bcf00] strm command p
[06:53:30.263060] process_strm:268 [0x4bcf00] pause (interval:0)
[06:53:30.263104] AVTBasic:201 [0x546ed0]: uPNP Pause (cookie 0x1e6)
[06:53:30.263452] sendSTAT:169 [0x4bcf00]: STAT:[STMp] msplayed 12000
[06:53:30.505845] _SyncNotifState:692 Wohnzimmer: uPNP pause

**Comment by philippe44** [comment]
I've not changed something in 1.80.2 that could explain. Can you verify the version you're using? Just erase the log and look at the very few lines after you've restarted the helper.

**Comment by rgreil** [comment]
Starting Squeeze2upnp: /usr/local/slimserver/Cache/InstalledPlugins/Plugins/UPnPBridge/Bin/squeeze2upnp-aarch64 -Z -I -f /usr/local/slimserver/Logs/upnpbridge.log -x /usr/local/slimserver/prefs/upnpbridge.xml
[09:10:02.196039] main:1771 Starting squeeze2upnp version: v1.80.3 (Nov 29 2021 @ 10:10:20)
[09:10:02.262184] output_init:652 success loading FLAC encoder
[09:10:02.267565] Start:1533 Binding to 192.168.1.15:49154 (http:0)
[09:10:05.716788] AddMRDevice:1420 [0x546ed0]: adding renderer (Wohnzimmer)
[09:10:05.726394] MasterHandler:1051 [0x546ed0]: subscribe success
[09:10:05.745330] slimproto:861 squeezelite [0x4bcf00] <=> player [0x546ed0]
[09:10:05.745412] slimproto:862 [0x4bcf00] connecting to 192.168.1.15:3483
[09:10:05.746019] slimproto:892 [0x4bcf00] connected
[09:10:05.746216] sendHELO:135 [0x4bcf00] cap: CanHTTPS=1,Model=squeezelite,ModelName=UPnPBridge,AccuratePlayPoints=0,HasDigitalOut=1,MaxSampleRate=48000,aac,alc,wav,aif,pcm,mp3

**Comment by philippe44** [comment]
Does it happen with flag or ogg streams or only with mp3?

**Comment by rgreil** [comment]
Do you have any url which I can test?

**Comment by philippe44** [comment]
Try Radio Paradise. Go on their web site and there is a page with all links to different formats

**Comment by rgreil** [comment]
You'r assumption is right. It seams to be related to mp3.
https://stream.radioparadise.com/rp_192.ogg plays and stops without issues.

**Comment by philippe44** [comment]
Can you then try a version 1.80.1 from here https://sourceforge.net/projects/lms-plugins-philippe44/files/UPnPBridge-1.80.1.zip/download and see what it does. This is the full package, you can unzip it in the plugin folder /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/UPnPBridge (maybe make a backup copy first, but you can always re-install it from the online version)

**Comment by rgreil** [comment]
Did not help. Based on the startup log it should use your version:

Starting Squeeze2upnp: /usr/local/slimserver/Cache/InstalledPlugins/Plugins/UPnPBridge/Bin/squeeze2upnp-aarch64 -Z -I -f /usr/local/slimserver/Logs/upnpbridge.log -x /usr/local/slimserver/prefs/upnpbridge.xml
[08:42:02.471157] main:1771 Starting squeeze2upnp version: v1.80.1 (Oct 10 2021 @ 21:10:43)
[08:42:02.537916] output_init:652 success loading FLAC encoder
[08:42:02.543181] Start:1533 Binding to 192.168.1.15:49152 (http:0)

Just the version date looks strange if you built it today

**Comment by philippe44** [comment]
No it's the old version. I just wanted to verify that the problem was not recent and it is not

**Comment by philippe44** [comment]
I've released a set of new versions. Can you give them a  try?

**Comment by rgreil** [comment]
Hi. Wich version should I test? LMS shows v1.82.2 as current version. Should I download another version?

**Comment by philippe44** [comment]
Go on the LMS forum and see the 1st post of the thread about this. Then add the dev repository to get new version

**Comment by rgreil** [comment]
Still the same issue in v2.0.5. After pressing stop, it takes about 15 seconds until the receiver really stops playing.

**Comment by philippe44** [comment]
Oh, one thing: can you try to stop playback, not pause it. To do this, clear the playlist from LMS

**Comment by rgreil** [comment]
Clearing the playlist immediatly stops playing.

**Comment by philippe44** [comment]
Ok, I'll build a version with a new option to transform pause into stop for web radios

**Comment by philippe44** [comment]
Can you try 2.0.6? There is a new option in settings

**Comment by rgreil** [comment]
Very good! I've set "live pause" to stop and now it's working fine again. Thanks a lot!
